// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0

package database

import (
	"database/sql"
	"time"

	"github.com/google/uuid"
)

type Human struct {
	ID         uuid.UUID      `json:"id"`
	Name       string         `json:"name"`
	Surname    string         `json:"surname"`
	Patronymic sql.NullString `json:"patronymic"`
	Age        int32          `json:"age"`
	Gender     string         `json:"gender"`
	Country    string         `json:"country"`
	CreatedAt  time.Time      `json:"created_at"`
}
