version: '3.8'

services:
  database:
    image: postgres
    container_name: database
    restart: always
    environment:
      POSTGRES_USER: test_user
      POSTGRES_PASSWORD: test_password
      POSTGRES_DB: test
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  human_api:
    build: .
    container_name: human_api
    ports:
      - "8080:8080"
    depends_on:
      - database
    env_file:
      - .env
    entrypoint: >
      sh -c "/go/bin/goose up &&
             ./cmd/main"

volumes:
  pgdata: